import project.com.controller.AreaController
import project.com.controller.CameraController
import project.com.controller.ComplainController
import project.com.controller.CrossroadController
import project.com.controller.DatasetController
import project.com.controller.FeedbackController
import project.com.controller.LoginController
import project.com.controller.PackageController
import project.com.controller.PurchaseController
import project.com.controller.TrafficPolicestationController
import project.com.controller.VideoController